# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

    config.vm.define "phpapacherewrite", autostart: false do |apache|
        apache.vm.provider "docker" do |d|
            d.build_dir = "./"
            d.build_args = "-t=phpapacherewrite"
            d.name = "phpapacherewrite"
            d.ports = ["9999:80"]
        end

        apache.vm.synced_folder "./", "/var/www/html"

    end
end